version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        
        depends_on: 
            - mongo

    web:
        build:
            context: ./server
        env_file: ./.env
        environment: 
            DB_HOST: mongo
            SERVER_PORT: 3000
        depends_on:
            - mongo-express
        ports:
            - 3000:3000